remote_theme: peterdesmet/petridish@1.1
title: Anwar Khan
description: Description that will appear below the title in the banner
background: /assets/img/banner_background_image.jpg
permalink: /about/
